# Generated by Django 4.2.15 on 2024-10-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=45)),
                ("password", models.CharField(max_length=45)),
            ],
        ),
    ]
