# Generated by Django 4.2.15 on 2024-10-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_alter_book_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("projectname", models.CharField(max_length=45)),
                ("projectteam", models.CharField(max_length=45)),
                ("projectpeople", models.IntegerField()),
                ("companysituation", models.CharField(max_length=255)),
                ("projectdescription", models.CharField(max_length=255)),
            ],
        ),
    ]
